/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presidentialelectionquizapp;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 * 03/12/18
 * @author Josh, x17521289
 * PresVoteGUI.java
 */
public class PresVoteGUI extends javax.swing.JFrame {

    /**
     * Creates new form OOPProjectGUI
     */
    public PresVoteGUI() {
        initComponents();
        File inFile;
        FileReader fr;
        BufferedReader br;
        String name; //variable to store the incoming name
        
        try{
            inFile = new File ("name.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            name = br.readLine();
            TF_3.setText(name);
            br.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,"Error Reading the file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vote1 = new javax.swing.JRadioButton();
        vote2 = new javax.swing.JRadioButton();
        vote3 = new javax.swing.JRadioButton();
        vote4 = new javax.swing.JRadioButton();
        vote5 = new javax.swing.JRadioButton();
        vote6 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        submitVote = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        TF_3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Presidential Election Vote");

        jLabel2.setToolTipText("");

        jLabel3.setToolTipText("");

        jLabel4.setToolTipText("");

        jLabel7.setToolTipText("");

        buttonGroup1.add(vote1);
        vote1.setText("Peter Casey");
        vote1.setToolTipText("");
        vote1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(vote2);
        vote2.setText("Gavin Duffy");
        vote2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vote2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(vote3);
        vote3.setText("Sean Gallaher");
        vote3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vote3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(vote4);
        vote4.setText("Michael D Higgins");
        vote4.setContentAreaFilled(false);
        vote4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vote4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(vote5);
        vote5.setText("Joan Freeman");
        vote5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(vote6);
        vote6.setText("Liadh Ní Riada");
        vote6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vote6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vote6ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel8.setText("Who Would you Vote For?");

        submitVote.setText("Submit");
        submitVote.setToolTipText("");
        submitVote.setActionCommand("");
        submitVote.setPreferredSize(new java.awt.Dimension(83, 23));
        submitVote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVoteActionPerformed(evt);
            }
        });

        nextBtn.setText("Next Page");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Quiz Taker:");

        TF_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_3ActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidentialelectionquizapp/newpackage/pete.jpg"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidentialelectionquizapp/newpackage/gav2.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidentialelectionquizapp/newpackage/sean.JPG"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidentialelectionquizapp/newpackage/mick.jpg"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidentialelectionquizapp/newpackage/Joan.jpg"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presidentialelectionquizapp/newpackage/liadh.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitVote, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(vote1)
                                    .addComponent(jLabel10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(vote2))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(vote3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel11)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel12)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vote4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel6)
                                    .addComponent(vote5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(399, 399, 399)
                                .addComponent(jLabel1)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7)
                            .addComponent(vote6)
                            .addComponent(jLabel15))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(TF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel12))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vote1)
                            .addComponent(vote2)
                            .addComponent(vote3)
                            .addComponent(vote4)
                            .addComponent(vote5)
                            .addComponent(vote6))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitVote, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote1ActionPerformed
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String vote = "Peter Casey";
        String pathname = "H:\\Object Oriented Programming\\PresidentialElectionQuizApp/vote.txt";
        
        File f = new File(pathname);
        try{
            if(f.exists()){
                f.delete();
            }
            outFile = new File("vote.txt");
            fw = new FileWriter(outFile, true);
            
            bw = new BufferedWriter(fw);
            bw.write(vote);
            bw.newLine();
            bw.close();
        } catch(IOException e){
             JOptionPane.showMessageDialog(null, "Error writing file");
        };
       
    }//GEN-LAST:event_vote1ActionPerformed

    private void vote3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote3ActionPerformed
        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String vote = "Sean Gallaher";
        String pathname = "H:\\Object Oriented Programming\\PresidentialElectionQuizApp/vote.txt";
        
        File f = new File(pathname);
        try{
            if(f.exists()){
                f.delete();
            }
            outFile = new File("vote.txt");
            fw = new FileWriter(outFile, true);
            
            bw = new BufferedWriter(fw);
            bw.write(vote);
            bw.newLine();
            bw.close();
        } catch(IOException e){
             JOptionPane.showMessageDialog(null, "Error writing file");
        }
    }//GEN-LAST:event_vote3ActionPerformed

    private void submitVoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVoteActionPerformed
        File inFile;
        FileReader fr;
        BufferedReader br;
        String vote; //variable to store the incoming name
        
        try{
            inFile = new File ("vote.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            vote = br.readLine();
            JOptionPane.showMessageDialog(null,"You have voted for "+ vote);
            br.close();
        }
        catch(IOException e){
            JOptionPane.showMessageDialog(null,"Error Reading the file");
        }
    }//GEN-LAST:event_submitVoteActionPerformed

    private void vote2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote2ActionPerformed
         File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String vote = "Gavin Duffy";
        String pathname = "H:\\Object Oriented Programming\\PresidentialElectionQuizApp/vote.txt";
        
        File f = new File(pathname);
        try{
            if(f.exists()){
                f.delete();
            }
            outFile = new File("vote.txt");
            fw = new FileWriter(outFile, true);
            
            bw = new BufferedWriter(fw);
            bw.write(vote);
            bw.newLine();
            bw.close();
        } catch(IOException e){
             JOptionPane.showMessageDialog(null, "Error writing file");
        }
    }//GEN-LAST:event_vote2ActionPerformed

    private void vote4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote4ActionPerformed
         File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String vote = "Micheal D Higgins";
        String pathname = "H:\\Object Oriented Programming\\PresidentialElectionQuizApp/vote.txt";
        
        File f = new File(pathname);
        try{
            if(f.exists()){
                f.delete();
            }
            outFile = new File("vote.txt");
            fw = new FileWriter(outFile, true);
            
            bw = new BufferedWriter(fw);
            bw.write(vote);
            bw.newLine();
            bw.close();
        } catch(IOException e){
             JOptionPane.showMessageDialog(null, "Error writing file");
        }
    }//GEN-LAST:event_vote4ActionPerformed

    private void vote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote5ActionPerformed
         File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String vote = "Joan Freeman";
        String pathname = "H:\\Object Oriented Programming\\PresidentialElectionQuizApp/vote.txt";
        
        File f = new File(pathname);
        try{
            if(f.exists()){
                f.delete();
            }
            outFile = new File("vote.txt");
            fw = new FileWriter(outFile, true);
            
            bw = new BufferedWriter(fw);
            bw.write(vote);
            bw.newLine();
            bw.close();
        } catch(IOException e){
             JOptionPane.showMessageDialog(null, "Error writing file");
        }
    }//GEN-LAST:event_vote5ActionPerformed

    private void vote6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vote6ActionPerformed
         File outFile;
        FileWriter fw;
        BufferedWriter bw;
        
        String vote = "Liadh Ní Riada";
        String pathname = "H:\\Object Oriented Programming\\PresidentialElectionQuizApp/vote.txt";
        
        File f = new File(pathname);
        try{
            if(f.exists()){
                f.delete();
            }
            outFile = new File("vote.txt");
            fw = new FileWriter(outFile, true);
            
            bw = new BufferedWriter(fw);
            bw.write(vote);
            bw.newLine();
            bw.close();
        } catch(IOException e){
             JOptionPane.showMessageDialog(null, "Error writing file");
        }
    }//GEN-LAST:event_vote6ActionPerformed

    private void TF_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_3ActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        this.setVisible(false);
        ResultsGUI s = new ResultsGUI();
        s.setVisible(true);
    }//GEN-LAST:event_nextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PresVoteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PresVoteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PresVoteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PresVoteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PresVoteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton submitVote;
    private javax.swing.JRadioButton vote1;
    private javax.swing.JRadioButton vote2;
    private javax.swing.JRadioButton vote3;
    private javax.swing.JRadioButton vote4;
    private javax.swing.JRadioButton vote5;
    private javax.swing.JRadioButton vote6;
    // End of variables declaration//GEN-END:variables
}
